# ----------------------------------------------------------------------------------------------------
# 如果有一些简单的网页改动，效果预览可以前往 https://www.w3schools.com/icons/tryit.asp?icon=fab_fa-twitter&unicon=f099
# 已知的html布局：
# 
# /_includes/head.html      浏览器标签栏
# 
# /_includes/about.html     关于作者页面
# /_includes/contact.html   联系作者页面
# /_includes/dropdown.html  下拉菜单布局，使用 {% include dropdown.html %}
# /_includes/footer.html    网站底边栏
# /_includes/navbar.html    网页顶部导航栏

# 配置表
# /_data/projects.yml       在Project页面中展示的Project配置
# 
# 子功能
# Disqus 网站留言系统 | disqus-shortname
# Google Analytics 数据分析 | google-analytics
# ----------------------------------------------------------------------------------------------------

markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Eric Chen 的笔记工厂
# Description of the Site
description: 人生而自由，却无往不在枷锁之中
# URL of Image of the Site
site-image: /assets/images/meta.png
# Keywords of the Site
site-keywords: Blog, Game, Game Dev, Unity,
# URL for the Image of custom Favicon
favicon-url: /assets/images/website/my_logo.webp

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/website/Background.webp # https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# 这个 contact me 页面的功能可以前往 /_includes/contact.html 文件进一步修改
# 定制页面图标可以前往 https://fontawesome.com/ 查看，替换其中类似 <i class="fab fa-facebook"> 的字段
# ----------------------------------------------------------------------------------------------------
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
# 如果想留下图标但不加数据，可以给个 / 符号
email: eric01cbymikufan@outlook.com # thedevslot@gmail.com
bilibili_uid: 32729713
facebook_username: # thedevslot
twitter_username:  # thedevslot
instagram_username: # thedevslot
linkedin_username:  # thedevslot
github_username:  # thedevslot
youtube_channel_id:  # UCk_93NXYP-U_AOB5GfWlOow
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: # UA-163806439-1

# Disqus 这是一个网站留言系统 官网 https://disqus.com/
disqus-shortname: # thedevslot

# 这个 about me 页面的功能可以前往 /_includes/about.html 文件进一步修改
# ----------------------------------------------------------------------------------------------------
# Name of the Author
author-name: Eric Chen
# URL for the Image of the Author
author-image: /assets/images/website/head.webp # /assets/images/logo.png # https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: 一个兴趣使然的菜鸡游戏制作人。
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/github00eric

# SASS
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
